import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const users = [
  {
    id: 1,
    name: "Jack",
    recentReview: {
      title: "Moon Knight",
      director: "James Gunn",
      lead: "Oscar Isaac"
    }
  },
  {
    id: 2,
    name: "Po",
    recentReview: {
      title: "Titanic",
      director: "James Cameron",
      lead: "Leonardo DiCaprio"
    }
  }
]

export default function Home({ data }) {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Project DMS</title>
        <meta name="description" content="Generated by create next app - An interface for manipulating the backend database" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          {data.results.map(movie => {
            return (
              <div>
                <h1>{movie.original_title}</h1>
                <Image src={`https://image.tmdb.org/t/p/original/${movie.poster_path}?api_key=2822f47ee1842d9d67fc358813953f45&language=en-US}`} width={500} height={500}/>
                <p>{movie.overview}</p>
                <p>Released {movie.release_date}</p>
              </div>
            )
          })}
        </header>
        <section>
        {users.map(user => {
          return (
            <div key={user.id}>
              <Link href={`/profiles/${user.id}`}>
                <a>
                  <h2>{user.name}</h2>
                  <h5>Last Movie Seen...</h5>
                  <p>{user.recentReview.title}</p>
                  <ul>
                    <li>Directed by {user.recentReview.director}</li>
                    <li>Starring {user.recentReview.lead}</li>
                  </ul>
                </a>
              </Link>
            </div>
          ) 
        })}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps({ params }) {
  const res = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=${process.env.MOVIES_API_KEY}&language=en-US&page=1`)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}