import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const users = [
  {
    id: 1,
    name: "Jack",
    recentReview: {
      title: "Moon Knight",
      director: "James Gunn",
      lead: "Oscar Isaac"
    }
  },
  {
    id: 2,
    name: "Po",
    recentReview: {
      title: "Titanic",
      director: "James Cameron",
      lead: "Leonardo DiCaprio"
    }
  }
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Project DMS</title>
        <meta name="description" content="Generated by create next app - An interface for manipulating the backend database" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          <h1>Hello!</h1>
        </header>
        <section>
        {users.map(user => {
          return (
            <div key={user.id}>
              <Link href={`/profiles/${user.id}`}>
                <a>
                  <h2>{user.name}</h2>
                  <h5>Last Movie Seen...</h5>
                  <p>{user.recentReview.title}</p>
                  <ul>
                    <li>Directed by {user.recentReview.director}</li>
                    <li>Starring {user.recentReview.lead}</li>
                  </ul>
                </a>
              </Link>
            </div>
          ) 
        })}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
